version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
